services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./Frontend:/usr/share/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile